basePath: /
definitions:
  main.authRequestOrResponse:
    properties:
      GUID:
        example: 026b1196-05fa-49ec-acad-bb09ad170148
        type: string
    required:
    - GUID
    type: object
  main.refreshRequest:
    properties:
      refresh_token:
        example: valid refresh token
        type: string
    required:
    - refresh_token
    type: object
  main.tokensResponse:
    properties:
      access:
        example: new access token
        type: string
      refresh:
        example: new refresh token
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для сервиса аутентификации
  title: Authentication Service API
  version: "1.0"
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Генерирует access и refresh токены
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.authRequestOrResponse'
      - description: User-Agent, проверяется в Refresh
        in: header
        name: User-Agent
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токены
          schema:
            $ref: '#/definitions/main.tokensResponse'
        "400":
          description: Bad request(GUID required)
        "500":
          description: Something went wrong
      summary: Аутентификация пользователя
      tags:
      - auth
  /api/currentUser:
    get:
      description: Возвращает GUID текущего аутентифицированного пользователя
      produces:
      - application/json
      responses:
        "200":
          description: GUID пользователя
          schema:
            $ref: '#/definitions/main.authRequestOrResponse'
        "401":
          description: Unauthorized access
      security:
      - ApiKeyAuth: []
      summary: Получение текущего пользователя
      tags:
      - user
  /api/deauthorize:
    post:
      description: Отзывает все токены пользователя
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized access
      security:
      - ApiKeyAuth: []
      summary: Деавторизация
      tags:
      - auth
  /api/refresh:
    post:
      consumes:
      - application/json
      description: Обновляет пару access и refresh токенов
      parameters:
      - description: Refresh токен
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.refreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Новые токены
          schema:
            $ref: '#/definitions/main.tokensResponse'
        "400":
          description: Bad request(refresh token required)
        "401":
          description: Unauthorized access
        "403":
          description: User agent changed
      security:
      - ApiKeyAuth: []
      summary: Обновление токенов
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Access
    type: apiKey
swagger: "2.0"
